VERSION = "2.0.0"
network_passphrase = "Public Global Stellar Network ; September 2015"
ORG_ID = "LEXAI-001"

[DOCUMENTATION]
ORG_NAME = "Lex AI Coin"
ORG_URL = "https://getlexaicoin.com"
ORG_DESCRIPTION = "Lex AI Coin is a decentralized token for AI-powered finance."
ORG_LOGO = "https://getlexaicoin.com/assets/lexaicoin-symbol.png"
ORG_PHYSICAL_ADDRESS = "Wallkill, NY"
ORG_PHONE_NUMBER = "+1-845-541-9492"
ORG_EMAIL = "keir1@hvc.rr.com"
documentation = "https://github.com/dancercasey/getlexaicoin/blob/main/README.md"

[[ACCOUNTS]]
address = "GA3DQRTXVLHWVRJ3DQQ4SVWYWL7BHOXIBHVZSRAPPTTOX2LYGGU7YWOB"

[[CURRENCIES]]
code = "LEX"
issuer = "GA3DQRTXVLHWVRJ3DQQ4SVWYWL7BHOXIBHVZSRAPPTTOX2LYGGU7YWOB"
display_decimals = 2
name = "Lex AI Coin"
desc = "A token for AI-driven financial ecosystems"
image = "https://getlexaicoin.com/assets/lexaicoin-symbol.png"
