VERSION="2.0.0"

[DOCUMENTATION]
ORG_NAME="Lex AI Coin"
ORG_URL="https://getlexaicoin.com"
ORG_DESCRIPTION="Lex AI Coin is a decentralized token for AI-powered finance."
ORG_LOGO="https://getlexaicoin.com/logo.png"
ORG_PHYSICAL_ADDRESS="Wallkill, NY"
ORG_PHONE_NUMBER="+1-845-541-9492"
ORG_EMAIL="keir1@hvc.rr.com"

[[CURRENCIES]]
code="LEX"
issuer="GBARTKDSGDQXNPY5XFJEACSNKRF7OU67A4O5IMHJUBJPZSC6ROM45LQ7"
display_decimals=2
name="Lex AI Coin"
desc="A token for AI-driven financial ecosystems"
image="https://getlexaicoin.com/lex.png"
