VERSION = "2025.10.21.03.00"
NETWORK_PASSPHRASE = "Public Global Stellar Network ; September 2015"
SIGNING_KEY = "GDN52ZWPZ54SB62RADM2ERMFG6CICOI53GA7PICZFOWLXIYRCZQIOYYS"
HORIZON_URL = "https://horizon.stellar.org"

ACCOUNTS = [
  "GDN52ZWPZ54SB62RADM2ERMFG6CICOI53GA7PICZFOWLXIYRCZQIOYYS" # Issuer only
]

[[CURRENCIES]]
code = "LEXX"
issuer = "GDN52ZWPZ54SB62RADM2ERMFG6CICOI53GA7PICZFOWLXIYRCZQIOYYS"
display_decimals = 7
name = "Lexxaicoin"
desc = "Validator-grade asset issued by Lexxaicoin for governance continuity and optics restoration"
image = "https://getlexxaicoin.com/logo.png"
conditions = "Only valid when issued by GDN52ZWPZ54SB62RADM2ERMFG6CICOI53GA7PICZFOWLXIYRCZQIOYYS"
fixed_number = 50000000000
is_unlimited = false

[[PRINCIPALS]]
name = "Lexxaicoin Governance Node"
email = "keir1@hvc.rr.com"
keybase = "lexxaicoin"
twitter = "lexxaicoin"
github = "lexxaicoin"

[[VALIDATORS]]
alias = "LEXX Core Validator"
display_name = "Lexxaicoin Validator Node"
public_key = "GDN52ZWPZ54SB62RADM2ERMFG6CICOI53GA7PICZFOWLXIYRCZQIOYYS"
host = "getlexxaicoin.com"
history = "https://getlexxaicoin.com/validator-history"
