VERSION = "2.0.0"

[DOCUMENTATION]
ORG_NAME = "Lex AI Coin"
ORG_URL = "https://getlexaicoin.com"
ORG_DESCRIPTION = "Lex AI Coin is a decentralized token for AI-powered finance."
ORG_LOGO = "https://getlexaicoin.com/assets/lexaicoin-symbol.png"
ORG_PHYSICAL_ADDRESS = "Wallkill, NY"
ORG_PHONE_NUMBER = "+1-845-541-9492"
ORG_EMAIL = "keir1@hvc.rr.com"
documentation = "https://github.com/dancercasey/getlexaicoin/blob/main/README.md"


[[CURRENCIES]]
code = "LEX"
issuer = "GA3DQRTXVLHWVRJ3DQQ4SVWYWL7BHOXIBHVZSRAPPTTOX2LYGGU7YWOB"
status = "live"
display_decimals = 2
name = "Lexaicoin"
desc = "Fixed supply of 50 billion LEX. Issuer wallet holds zero tokens. No further issuance possible."
conditions = "All tokens distributed. Asset supply is immutable by governance. Trustlines open."
# Updated Sept 23, 2025 – switched to PNG for platform compatibility
image = "https://getlexaicoin.com/assets/lexaicoin-symbol.png"


[[ACCOUNTS]]
address = "GA3DQRTXVLHWVRJ3DQQ4SVWYWL7BHOXIBHVZSRAPPTTOX2LYGGU7YWOB"  # Issuer

[[ACCOUNTS]]
address = "GBARTKDSGDQXNPY5XFJEACSNKRF7OU67A4O5IMHJUBJPZSC6ROM45LQ7"  # Distributor

[[ACCOUNTS]]
public_key = "GDA3A3EC5KW6VGYNHE7SLCSXPLVQPAEQURNHY3GTFVF3BFR7MEUCPCTO"
role = "market"
