VERSION="2.0.0"

[DOCUMENTATION]
ORG_NAME="Lex AI Coin"
ORG_URL="https://getlexaicoin.com"
ORG_DESCRIPTION="Lex AI Coin is a decentralized token for AI-powered finance."
ORG_LOGO="https://getlexaicoin.com/logo.png"
ORG_PHYSICAL_ADDRESS="Wallkill, NY"
ORG_PHONE_NUMBER="+1-845-541-9492"
ORG_EMAIL="keir1@hvc.rr.com"

[[CURRENCIES]]
code = "LEX"
issuer = "GBUGRKYZANCEADQ2P46LZQBOBNQVHSF2CYA3LROXJEJAS6ENVIF2EJED"
display_decimals = 2
name = "LEX Coin"
desc = "Deflationary token issued on Stellar. Supply capped at 50B. No inflation."
image = "https://getlexaicoin.com/lex.png"

[[ACCOUNTS]]
address = "GA3DQRTXVLHWVRJ3DQQ4SVWYWL7BHOXIBHVZSRAPPTTOX2LYGGU7YWOB"
