VERSION = "2.0.0"

[DOCUMENTATION]
ORG_NAME = "Lexaicoin"
ORG_URL = "https://getlexaicoin.com"
ORG_DESCRIPTION = "Validator-grade asset with timestamped governance, symbolic scarcity, and optics restoration"
ORG_LOGO = "https://getlexaicoin.com/logo.png"
ORG_PHYSICAL_ADDRESS = "Validator-grade governance node"
ORG_OFFICIAL_EMAIL = "support@getlexaicoin.com"

[[ACCOUNTS]]
address = "GCAX7S3HBCFNZFISJUVOYUQSAITJVBRX4OXQ6W3SXJ6X4APMCAJLZX4M"
role = "issuer"

[[CURRENCIES]]
code = "LEX"
issuer = "GCAX7S3HBCFNZFISJUVOYUQSAITJVBRX4OXQ6W3SXJ6X4APMCAJLZX4M"
display_decimals = 2
name = "Lexaicoin"
desc = "Capped, deflationary token engineered for transparency, auditability, and symbolic clarity"
image = "https://getlexaicoin.com/logo.png"
conditions = "Issued under validator-grade governance protocols. No inflation. No reissuance. No scheduled unlocks."
fixed_number = "50000000000"
is_unlimited = false

[PRINCIPALS]
name = "Validator Governance Node"
email = "support@getlexaicoin.com"
twitter = "@LEXCoinOfficial"
telegram = "https://t.me/LEXCoinOfficial"
github = "https://github.com/dancercasey/getlexaicoin"
